#! tvf
namespace import tvf::VERBATIM tvf::LAYOUT tvf::DRC

LAYOUT SYSTEM GDSII
LAYOUT PATH '/home/user3/project/CX200UR1/CX200UR1_SOC_TOP/pv/dataout/0216/gds/CX200A_SOC_TOP_wi_dm.gds'
#LAYOUT PATH '/home/user3/project/CX200UR1/CX200UR1_SOC_TOP/pv/dataout/$env(DATAOUT_VERSION)/gds/$env(DESIGN).MergeDMDP.gds.gz'
LAYOUT PRIMARY $env(DESIGN)


DRC RESULTS DATABASE '/home/user3/project/CX200UR1/CX200UR1_SOC_TOP/pv/pv/db/$env(DATAOUT_VERSION)/ant/$env(DESIGN).ANT.db'
DRC SUMMARY REPORT '/home/user3/project/CX200UR1/CX200UR1_SOC_TOP/pv/pv/rpt/$env(DATAOUT_VERSION)/ant/$env(DESIGN).ANT.rep'  // HIER

VERBATIM {

//VARIABLE PAD_TEXT ""
//VARIABLE VSS_TEXT ""
//VARIABLE VDD_TEXT ""

DRC CHECK TEXT ALL
DRC MAXIMUM RESULTS ALL

//INCLUDE "/home/user3/project/CX200UR1/CX200UR1_SOC_TOP/pv/scr/CLN28HP_8M_002_ANT.20b"
INCLUDE "/home/user3/project/CX200UR1/CX200UR1_SOC_TOP/pv/scr/CLN28HP_8M_002_ANT.22a"
}

