set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_00}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_01}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_02}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_03}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_04}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_05}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_06}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_07}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_08}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_09}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_10}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_11}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_12}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_13}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_14}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_15}]
set_clock_uncertainty -hold  0.05 [get_clocks {ac_hocc_16}]
set_clock_uncertainty -hold  0.05 [get_clocks {ahb_clk_bb}]
set_clock_uncertainty -hold  0.05 [get_clocks {ahb_clk_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {ahb_clk_rc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {ap_swclk_gpio0}]
set_clock_uncertainty -hold  0.05 [get_clocks {ap_swclk_gpio12}]
set_clock_uncertainty -hold  0.05 [get_clocks {ap_swclk_gpio16}]
set_clock_uncertainty -hold  0.05 [get_clocks {ap_swclk_gpio4}]
set_clock_uncertainty -hold  0.05 [get_clocks {ap_swclk_gpio8}]
set_clock_uncertainty -hold  0.05 [get_clocks {ap_swclk_mux_gpio0}]
set_clock_uncertainty -hold  0.05 [get_clocks {ap_swclk_mux_gpio12}]
set_clock_uncertainty -hold  0.05 [get_clocks {ap_swclk_mux_gpio16}]
set_clock_uncertainty -hold  0.05 [get_clocks {ap_swclk_mux_gpio4}]
set_clock_uncertainty -hold  0.05 [get_clocks {ap_swclk_mux_gpio8}]
set_clock_uncertainty -hold  0.05 [get_clocks {apb_clk_bb}]
set_clock_uncertainty -hold  0.05 [get_clocks {apb_clk_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {apb_clk_rc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {bb_clk_afe_rxcal_2}]
set_clock_uncertainty -hold  0.05 [get_clocks {bb_clk_afe_rxcal_3}]
set_clock_uncertainty -hold  0.05 [get_clocks {bb_clk_afe_rx}]
set_clock_uncertainty -hold  0.05 [get_clocks {bb_clk_afe_tx_inv}]
set_clock_uncertainty -hold  0.05 [get_clocks {bb_clk}]
set_clock_uncertainty -hold  0.05 [get_clocks {can_clk_plldiv}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_124m8}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_32k_mux_rc}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_32k_mux_xo}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_dbb_adc250m}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_dbb_afe_apb_div_bb}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_dbb_afe_apb_div_rc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_dbb_afe_apb_inv_bb}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_dbb_afe_apb_inv_rc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_dbb_ppm125m}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_dbb_trm}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_dbb_tx}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_mbist_tck_mux}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_mbist_tck}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_muxcap_adc250m}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_muxcap_hclk}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_muxcap_ppm125m}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_qspi_sclk_out_pad}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_qspi_sclk_out}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_ref_qspi_pll}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_ref_qspi_rc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_soc_afe_apb_div_bb}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_soc_afe_apb_div_rc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_soc_afe_apb_inv_bb}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_soc_afe_apb_inv_rc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_ssp_sclk_out_pad0}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_ssp_sclk_out_pad12}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_ssp_sclk_out_pad16}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_ssp_sclk_out_pad4}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_ssp_sclk_out_pad8}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_ssp_sclk_out}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_sts_mem_hclk}]
set_clock_uncertainty -hold  0.05 [get_clocks {clk_sts_mem_ppm125m}]
set_clock_uncertainty -hold  0.05 [get_clocks {cp_clk_bb}]
set_clock_uncertainty -hold  0.05 [get_clocks {cp_clk_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {cp_clk_rc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {cp_swclk_boot}]
set_clock_uncertainty -hold  0.05 [get_clocks {cp_swclk_gpio10}]
set_clock_uncertainty -hold  0.05 [get_clocks {cp_swclk_gpio14}]
set_clock_uncertainty -hold  0.05 [get_clocks {cp_swclk_gpio2}]
set_clock_uncertainty -hold  0.05 [get_clocks {cp_swclk_gpio6}]
set_clock_uncertainty -hold  0.05 [get_clocks {cp_swclk_mux_boot}]
set_clock_uncertainty -hold  0.05 [get_clocks {cp_swclk_mux_gpio10}]
set_clock_uncertainty -hold  0.05 [get_clocks {cp_swclk_mux_gpio14}]
set_clock_uncertainty -hold  0.05 [get_clocks {cp_swclk_mux_gpio2}]
set_clock_uncertainty -hold  0.05 [get_clocks {cp_swclk_mux_gpio6}]
set_clock_uncertainty -hold  0.05 [get_clocks {gpadc_2m_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {gpio_irq_clk}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_master_mclk}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_master_sclk_inv}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_master_sclk_mux}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_master_sclk_out_pad10}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_master_sclk_out_pad16}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_master_sclk_out_pad4}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_master_sclk}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_slave_clk_gpio10}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_slave_clk_gpio16}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_slave_clk_gpio4}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_slave_ext_clk_gpio10}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_slave_ext_clk_gpio16}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_slave_ext_clk_gpio4}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_slave_sclk_inv_gpio10}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_slave_sclk_inv_gpio16}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_slave_sclk_inv_gpio4}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_slave_sclk_mux_gpio10}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_slave_sclk_mux_gpio16}]
set_clock_uncertainty -hold  0.05 [get_clocks {i2s_slave_sclk_mux_gpio4}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_can_clk_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_can_clk_pll}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_can_clk_rc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_clk_cal_fast_bb}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_clk_cal_fast_xo38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_clk_cal_slow_rc32k}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_clk_cal_slow_rc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_clk_cal_slow_xo32k}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_i2c0_124m8}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_i2c0_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_i2c1_124m8}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_i2c1_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_spim_124m8}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_spim_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_spis_124m8}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_spis_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_sys_clk_bb}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_sys_clk_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_sys_clk_rc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_timer0_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_timer0_rc32k}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_timer1_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_timer1_rc32k}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_timer2_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_timer2_rc32k}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_uart0_124m8}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_uart0_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_uart1_124m8}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_uart1_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_wwdt_osc38m}]
set_clock_uncertainty -hold  0.05 [get_clocks {mux_wwdt_rc32k}]
set_clock_uncertainty -hold  0.05 [get_clocks {osc32k_clk}]
set_clock_uncertainty -hold  0.05 [get_clocks {osc38m_clk}]
set_clock_uncertainty -hold  0.05 [get_clocks {ram10_clk_ap}]
set_clock_uncertainty -hold  0.05 [get_clocks {ram10_clk_cp}]
set_clock_uncertainty -hold  0.05 [get_clocks {ram3_clk_ap}]
set_clock_uncertainty -hold  0.05 [get_clocks {ram3_clk_cp}]
set_clock_uncertainty -hold  0.05 [get_clocks {ram4_clk_ap}]
set_clock_uncertainty -hold  0.05 [get_clocks {ram4_clk_cp}]
set_clock_uncertainty -hold  0.05 [get_clocks {ram5_clk_ap}]
set_clock_uncertainty -hold  0.05 [get_clocks {ram5_clk_cp}]
set_clock_uncertainty -hold  0.05 [get_clocks {ram9_clk_ap}]
set_clock_uncertainty -hold  0.05 [get_clocks {ram9_clk_cp}]
set_clock_uncertainty -hold  0.05 [get_clocks {rc32k_clk}]
set_clock_uncertainty -hold  0.05 [get_clocks {rc38m_clk}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_00}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_01}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_02}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_03}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_04}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_05}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_06}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_07}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_08}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_09}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_10}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_11}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_12}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_13}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_14}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_15}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_hocc_16}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_00}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_01}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_02}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_03}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_04}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_05}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_06}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_07}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_08}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_09}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_10}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_11}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_12}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_13}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_14}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_15}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_16}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_17}]
set_clock_uncertainty -hold  0.05 [get_clocks {sa_locc_18}]
set_clock_uncertainty -hold  0.05 [get_clocks {scan_clk}]
set_clock_uncertainty -hold  0.05 [get_clocks {sdio_clk_gpio0}]
set_clock_uncertainty -hold  0.05 [get_clocks {sdio_clk_gpio12}]
set_clock_uncertainty -hold  0.05 [get_clocks {sdio_clk_gpio6}]
set_clock_uncertainty -hold  0.05 [get_clocks {sdio_clk_inv_gpio0}]
set_clock_uncertainty -hold  0.05 [get_clocks {sdio_clk_inv_gpio12}]
set_clock_uncertainty -hold  0.05 [get_clocks {sdio_clk_inv_gpio6}]
set_clock_uncertainty -hold  0.05 [get_clocks {sdio_clk_mux_gpio0}]
set_clock_uncertainty -hold  0.05 [get_clocks {sdio_clk_mux_gpio12}]
set_clock_uncertainty -hold  0.05 [get_clocks {sdio_clk_mux_gpio6}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_00}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_01}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_02}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_03}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_04}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_05}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_06}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_07}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_08}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_09}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_10}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_11}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_12}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_13}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_14}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_15}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_hocc_16}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_00}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_01}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_02}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_03}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_04}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_05}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_06}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_07}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_08}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_09}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_10}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_11}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_12}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_13}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_14}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_15}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_16}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_17}]
set_clock_uncertainty -hold  0.05 [get_clocks {shift_locc_18}]
set_clock_uncertainty -hold  0.05 [get_clocks {spim_sclk_gpio0}]
set_clock_uncertainty -hold  0.05 [get_clocks {spim_sclk_gpio12}]
set_clock_uncertainty -hold  0.05 [get_clocks {spim_sclk_gpio16}]
set_clock_uncertainty -hold  0.05 [get_clocks {spim_sclk_gpio4}]
set_clock_uncertainty -hold  0.05 [get_clocks {spim_sclk_gpio8}]
set_clock_uncertainty -hold  0.05 [get_clocks {spim_sclk_mux_gpio0}]
set_clock_uncertainty -hold  0.05 [get_clocks {spim_sclk_mux_gpio12}]
set_clock_uncertainty -hold  0.05 [get_clocks {spim_sclk_mux_gpio16}]
set_clock_uncertainty -hold  0.05 [get_clocks {spim_sclk_mux_gpio4}]
set_clock_uncertainty -hold  0.05 [get_clocks {spim_sclk_mux_gpio8}]
set_clock_uncertainty -hold  0.05 [get_clocks {spis_sclk_gpio0}]
set_clock_uncertainty -hold  0.05 [get_clocks {spis_sclk_gpio12}]
set_clock_uncertainty -hold  0.05 [get_clocks {spis_sclk_gpio16}]
set_clock_uncertainty -hold  0.05 [get_clocks {spis_sclk_gpio4}]
set_clock_uncertainty -hold  0.05 [get_clocks {spis_sclk_gpio8}]
set_clock_uncertainty -hold  0.05 [get_clocks {spis_sclk_mux_gpio0}]
set_clock_uncertainty -hold  0.05 [get_clocks {spis_sclk_mux_gpio12}]
set_clock_uncertainty -hold  0.05 [get_clocks {spis_sclk_mux_gpio16}]
set_clock_uncertainty -hold  0.05 [get_clocks {spis_sclk_mux_gpio4}]
set_clock_uncertainty -hold  0.05 [get_clocks {spis_sclk_mux_gpio8}]
set_clock_uncertainty -hold  0.05 [get_clocks {testspi_clk0}]
set_clock_uncertainty -hold  0.05 [get_clocks {testspi_clk_mux}]
set_clock_uncertainty -hold  0.05 [get_clocks {testspi_clk}]
set_clock_uncertainty -hold  0.05 [get_clocks {txcal_cnt_clk_neg}]
set_clock_uncertainty -hold  0.05 [get_clocks {txcal_cnt_clk_pos}]
set_clock_uncertainty -hold  0.05 [get_clocks {txcal_cnt_clk}]
set_clock_uncertainty -hold  0.05 [get_clocks {vir_clk}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_00}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_01}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_02}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_03}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_04}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_05}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_06}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_07}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_08}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_09}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_10}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_11}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_12}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_13}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_14}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_15}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ac_hocc_16}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {ahb_clk_bb}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {bb_clk_afe_rx}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {bb_clk}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {can_clk_plldiv}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {clk_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {clk_dbb_adc250m}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {clk_dbb_ppm125m}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {clk_dbb_tx}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {clk_qspi_sclk_out_pad}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {clk_qspi_sclk_out}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {clk_ref_qspi_pll}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {cp_clk_bb}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {mux_can_clk_pll}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {mux_clk_cal_fast_bb}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {mux_i2c0_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {mux_i2c1_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {mux_spim_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {mux_spis_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {mux_sys_clk_bb}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {mux_uart0_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {mux_uart1_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_00}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_01}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_02}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_03}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_04}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_05}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_06}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_07}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_08}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_09}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_10}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_11}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_12}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_13}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_14}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_15}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_hocc_16}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_00}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_01}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_02}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_03}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_04}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_05}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_06}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_07}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_08}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_09}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_10}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_11}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_12}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_13}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_14}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_15}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_16}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_17}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {sa_locc_18}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {scan_clk}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_00}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_01}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_02}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_03}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_04}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_05}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_06}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_07}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_08}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_09}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_10}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_11}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_12}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_13}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_14}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_15}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_hocc_16}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_00}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_01}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_02}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_03}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_04}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_05}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_06}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_07}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_08}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_09}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_10}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_11}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_12}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_13}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_14}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_15}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_16}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_17}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {shift_locc_18}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {testspi_clk0}]
set_clock_uncertainty -setup  [expr 0.05+0.2] [get_clocks {vir_clk}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {ahb_clk_bb}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {apb_clk_bb}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {bb_clk_afe_rxcal_2}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {bb_clk_afe_rxcal_3}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {bb_clk_afe_rx}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {bb_clk_afe_tx_inv}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {bb_clk}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {can_clk_plldiv}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_dbb_adc250m}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_dbb_afe_apb_div_bb}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_dbb_afe_apb_inv_bb}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_dbb_ppm125m}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_dbb_trm}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_dbb_tx}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_muxcap_adc250m}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_muxcap_hclk}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_muxcap_ppm125m}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_qspi_sclk_out_pad}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_qspi_sclk_out}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_ref_qspi_pll}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_soc_afe_apb_div_bb}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_soc_afe_apb_inv_bb}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_ssp_sclk_out_pad0}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_ssp_sclk_out_pad12}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_ssp_sclk_out_pad16}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_ssp_sclk_out_pad4}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_ssp_sclk_out_pad8}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_ssp_sclk_out}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_sts_mem_hclk}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {clk_sts_mem_ppm125m}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {cp_clk_bb}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {i2s_master_mclk}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {i2s_master_sclk_inv}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {i2s_master_sclk_mux}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {i2s_master_sclk_out_pad10}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {i2s_master_sclk_out_pad16}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {i2s_master_sclk_out_pad4}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {i2s_master_sclk}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {mux_can_clk_pll}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {mux_clk_cal_fast_bb}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {mux_i2c0_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {mux_i2c1_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {mux_spim_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {mux_spis_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {mux_sys_clk_bb}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {mux_uart0_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {mux_uart1_124m8}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {ram10_clk_ap}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {ram10_clk_cp}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {ram3_clk_ap}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {ram3_clk_cp}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {ram4_clk_ap}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {ram4_clk_cp}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {ram5_clk_ap}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {ram5_clk_cp}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {ram9_clk_ap}]
set_clock_uncertainty -setup  [expr 0.05+0.235] [get_clocks {ram9_clk_cp}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {ahb_clk_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {ahb_clk_rc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {ap_swclk_gpio0}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {ap_swclk_gpio12}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {ap_swclk_gpio16}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {ap_swclk_gpio4}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {ap_swclk_gpio8}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {ap_swclk_mux_gpio0}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {ap_swclk_mux_gpio12}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {ap_swclk_mux_gpio16}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {ap_swclk_mux_gpio4}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {ap_swclk_mux_gpio8}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {apb_clk_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {apb_clk_rc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {clk_32k_mux_rc}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {clk_32k_mux_xo}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {clk_dbb_afe_apb_div_rc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {clk_dbb_afe_apb_inv_rc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {clk_mbist_tck_mux}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {clk_mbist_tck}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {clk_ref_qspi_rc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {clk_soc_afe_apb_div_rc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {clk_soc_afe_apb_inv_rc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {cp_clk_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {cp_clk_rc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {cp_swclk_boot}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {cp_swclk_gpio10}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {cp_swclk_gpio14}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {cp_swclk_gpio2}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {cp_swclk_gpio6}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {cp_swclk_mux_boot}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {cp_swclk_mux_gpio10}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {cp_swclk_mux_gpio14}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {cp_swclk_mux_gpio2}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {cp_swclk_mux_gpio6}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {gpadc_2m_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {gpio_irq_clk}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {i2s_slave_clk_gpio10}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {i2s_slave_clk_gpio16}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {i2s_slave_clk_gpio4}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {i2s_slave_ext_clk_gpio10}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {i2s_slave_ext_clk_gpio16}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {i2s_slave_ext_clk_gpio4}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {i2s_slave_sclk_inv_gpio10}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {i2s_slave_sclk_inv_gpio16}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {i2s_slave_sclk_inv_gpio4}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {i2s_slave_sclk_mux_gpio10}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {i2s_slave_sclk_mux_gpio16}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {i2s_slave_sclk_mux_gpio4}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_can_clk_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_can_clk_rc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_clk_cal_fast_xo38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_clk_cal_slow_rc32k}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_clk_cal_slow_rc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_clk_cal_slow_xo32k}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_i2c0_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_i2c1_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_spim_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_spis_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_sys_clk_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_sys_clk_rc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_timer0_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_timer0_rc32k}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_timer1_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_timer1_rc32k}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_timer2_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_timer2_rc32k}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_uart0_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_uart1_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_wwdt_osc38m}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {mux_wwdt_rc32k}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {osc32k_clk}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {osc38m_clk}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {rc32k_clk}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {rc38m_clk}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {sdio_clk_gpio0}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {sdio_clk_gpio12}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {sdio_clk_gpio6}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {sdio_clk_inv_gpio0}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {sdio_clk_inv_gpio12}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {sdio_clk_inv_gpio6}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {sdio_clk_mux_gpio0}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {sdio_clk_mux_gpio12}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {sdio_clk_mux_gpio6}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spim_sclk_gpio0}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spim_sclk_gpio12}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spim_sclk_gpio16}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spim_sclk_gpio4}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spim_sclk_gpio8}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spim_sclk_mux_gpio0}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spim_sclk_mux_gpio12}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spim_sclk_mux_gpio16}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spim_sclk_mux_gpio4}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spim_sclk_mux_gpio8}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spis_sclk_gpio0}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spis_sclk_gpio12}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spis_sclk_gpio16}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spis_sclk_gpio4}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spis_sclk_gpio8}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spis_sclk_mux_gpio0}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spis_sclk_mux_gpio12}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spis_sclk_mux_gpio16}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spis_sclk_mux_gpio4}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {spis_sclk_mux_gpio8}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {testspi_clk_mux}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {testspi_clk}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {txcal_cnt_clk_neg}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {txcal_cnt_clk_pos}]
set_clock_uncertainty -setup  [expr 0.05+0.335] [get_clocks {txcal_cnt_clk}]

