VPATH 		:= ./FLAG
DESIGN 		:= SC5018_TOP
VERSION 	:= test_flow
NUM_CORE 	:= 8

def_file 	:= 
gds_file 	:= 
gds_layer_map_file 	:= 
mapping_file 				:= 
corner_file					:= 
selected_corners 		:=
run_dir 						:= ./$(VERSION)/

