#!/bin/tclsh
# --------------------------
# author    : sar song
# date      : 2025/09/24 15:12:23 Wednesday
# label     : misc_proc
#   tcl  -> (atomic_proc|display_proc|gui_proc|task_proc|dump_proc|check_proc|math_proc|package_proc|test_proc|datatype_proc|db_proc|flow_proc|report_proc|cross_lang_proc|misc_proc)
#   perl -> (format_sub|getInfo_sub|perl_task)
# descrip   : Obtain the path pins that need to be highlighted from the report_timing (rpt) file of PT, and different paths can be automatically split based on keywords.
# return    : lists of even pins
# ref       : link url
# --------------------------
source ./common/split_timing_path.common.tcl; # split_timing_path
proc genCmd_getPurePinOfPath_fromTimingPathReport {args} {
  set reportTimingFile   ""
  set lineExpToSplitPath {^TE} ; # used to regexp
  set stdcellExp         {.*D\d+BWP(LVT)?} ; # don't use char '^' or '$'
  set startOfPath        {Point\s+} ; # end expression of launch timing path
  set endOfPath          {data arrival time} ; # end expression of launch timing path
  parse_proc_arguments -args $args opt
  foreach arg [array names opt] {
    regsub -- "-" $arg "" var
    set $var $opt($arg)
  }
  if {![file isfile $reportTimingFile]} {
    error "proc genCmd_getPurePinOfPath_fromTimingPathReport: check your input: file name ($reportTimingFile) is not found!!!" 
  }
  set fi [open $reportTimingFile r]
  set content [split [read $fi] \n]
  set stdcellExpToMatchLine [subst -nocommands -nobackslashes {($stdcellExp)}]
  set pinLines [lmap templine $content {
    if {[regexp $lineExpToSplitPath|$stdcellExpToMatchLine|$startOfPath|$endOfPath $templine]} {
      set temp $templine 
    }
  }]
  set purePinListWithSplieLine [lmap templine $pinLines {
    if {[regexp {^\s*$} $templine]} { continue }
    set indexOfStdCell [lsearch -regexp $templine $stdcellExpToMatchLine]
    if {$indexOfStdCell == -1} { 
      if {[regexp $startOfPath $templine]} { 
        set temp "START" 
      } elseif {[regexp $endOfPath $templine]} {
        set temp "END" 
      } elseif {[regexp $lineExpToSplitPath $templine]} {
        set temp "SPLIT"
      }
    } else {
      set pinName [lindex $templine [expr {$indexOfStdCell - 1}]]
    }
  }]
  set splitedPinList [split_timing_path $purePinListWithSplieLine]
  set filteredPinList [lmap tempList $splitedPinList {
    if {[llength $tempList] == 1} { continue } else {
      if {[join [lrange [split [lindex $tempList 0] "/"] 0 end-1] "/"] eq [join [lrange [split [lindex $tempList 1] "/"] 0 end-1] "/"]} {
        set tempList [lrange $tempList 1 end] 
      }
    }
  }]
  return $splitedPinList
}

define_proc_arguments genCmd_getPurePinOfPath_fromTimingPathReport \
  -info "gen cmd for geting pure pin of path from timing path report, \n\t \
  Notice: This proc uses the report_timing rpt file generated by PT to match and \
  obtain pin names. It must display both the input pin and output pin names of the \
  inst, and must not only show the output pin name. In addition, after the pin name, \
  there must be a number of spaces followed by the format '(stdCellName)', because \
  the proc uses this positional relationship to obtain the pin name."\
  -define_args {
    {-reportTimingFile "specify the file name of report_timing" AString string optional}
    {-lineExpToSplitPath "specify expression of spliting timing path" AString string optional}
    {-stdcellExp "specify the expression of match stdcell name(of LibCells)" AString string optional}
  }
