#!/bin/tclsh
# --------------------------
# author    : sar song
# date      : 2025/09/24 19:00:22 Wednesday
# label     : gui_proc
#   tcl  -> (atomic_proc|display_proc|gui_proc|task_proc|dump_proc|check_proc|math_proc|package_proc|test_proc|datatype_proc|db_proc|flow_proc|report_proc|cross_lang_proc|misc_proc)
#   perl -> (format_sub|getInfo_sub|perl_task)
# descrip   : Obtain the paths that need to be highlighted based on the report_timing RPT file generated by PT.
# return    : cmds list
# ref       : link url
# --------------------------
proc genCmd_highlightTimingPathBasedOnReportFile {args} {
  set reportTimingFile   ""
  set lineExpToSplitPath {^TE} ; # used to regexp
  set stdcellExp         {.*D\d+BWP(LVT)?} ; # don't use char '^' or '$'
  set startOfPath        {Point\s+} ; # end expression of launch timing path
  set endOfPath          {data arrival time} ; # end expression of launch timing path
  set modeOfConnect "whole_net" ; # whole_net|flight_line
  set ifWithArrow   1; # 1|0
  set colorsIndexLoopListsForNet {60 50 62 63 61 55 52 4 6 14 15 17 28 29 31 56 57 61 64 42} ; # 20 items
  set colorsIndexLoopListsForInst {1 2 3 5 7 9 10 11 14 15 17 19 20 21 24 22 25 28 30 32} ; # 20 items
  parse_proc_arguments -args $args opt
  foreach arg [array names opt] {
    regsub -- "-" $arg "" var
    set $var $opt($arg)
  }
  set evenNumberLists [genCmd_getPurePinOfPath_fromTimingPathReport -reportTimingFile $reportTimingFile -lineExpToSplitPath $lineExpToSplitPath -stdcellExp $stdcellExp \
                        -startOfPath $startOfPath -endOfPath $endOfPath]
  set cmdsList [list]
  set i 0
  foreach tempEvenNumberList $evenNumberLists {
    set tempCmdsList [genCmd_highlightTimingPathBasedOnListOfEvenNumberedItems -evenNumberList $tempEvenNumberList -modeOfConnect $modeOfConnect -ifWithArrow $ifWithArrow \
                          -colorsIndexLoopListsForNet $colorsIndexLoopListsForNet -colorsIndexLoopListsForInst $colorsIndexLoopListsForInst -indexOfColorsForNetInst $i]
    incr i
    lappend cmdsList {*}$tempCmdsList
  }
  return $cmdsList
}

define_proc_arguments genCmd_highlightTimingPathBasedOnReportFile \
  -info "gen cmd for highlighting timing path based on reprot file"\
  -define_args {
    {-reportTimingFile "specify the file name of report_timing" AString string optional}
    {-lineExpToSplitPath "specify expression of spliting timing path" AString string optional}
    {-stdcellExp "specify the expression of match stdcell name(of LibCells)" AString string optional}
    {-startOfPath "specify the start expression of timing path" AString string optional}
    {-endOfPath "specify the end expression of timing path" AString string optional}
    {-modeOfConnect "specify the type of eco" oneOfString one_of_string {optional value_type {values {whole_net flight_line}}}}
    {-ifWithArrow "if using arrow on line" oneOfString one_of_string {optional value_type {values {1 0}}}}
    {-colorsIndexLoopListsForNet "specify the colors index loop lists for net color" AList list optional}
    {-colorsIndexLoopListsForInst "specify the colors index loop lists for inst color" AList list optional}
    {-indexOfColorsForNetInst "specify the index of Net and Inst color, it can get index with circle" AInt int optional}
  }

#!/bin/tclsh
# --------------------------
# author    : sar song
# date      : 2025/09/24 20:27:30 Wednesday
# label     : gui_proc
#   tcl  -> (atomic_proc|display_proc|gui_proc|task_proc|dump_proc|check_proc|math_proc|package_proc|test_proc|datatype_proc|db_proc|flow_proc|report_proc|cross_lang_proc|misc_proc)
#   perl -> (format_sub|getInfo_sub|perl_task)
# descrip   : Input a pin name list to obtain the positions and connections of the pins. Add markers and text at appropriate positions to label the path delay values.
# return    : cmds list
# ref       : link url
# --------------------------
source ./common/add_markers_and_text_for_point_list.common.tcl; # add_markers_and_text_for_point_list
proc genCmd_genMarkersAndTextOfPathDelay {args} {
  set typeForMarkersAndText "add" ; # add|delete
  set evenNumberList        {}
  set textList              {}
  set minLengthOfLine       0.7
  set sizeOfText             {} 
  set layerOfText           8 ; # routing layer name, can also use number
  set ifAddMarkersForPin    1 ; # 1|0
  set color                 "cyan" ; # red blue green yellow magenta cyan pink orange brown purple violet teal olive gold maroon wheat
  set markerShapeType       "STAR" ; # X|TICK|STAR
  parse_proc_arguments -args $args opt
  foreach arg [array names opt] {
    regsub -- "-" $arg "" var
    set $var $opt($arg)
  }
  if {![llength $evenNumberList]} {
    error "proc genCmd_genMarkersAndTextOfPathDelay: check your input : evenNumberList($evenNumberList) is empty!!!" 
  }
  if {[llength $evenNumberList] != [llength $textList]} {
    error "proc genCmd_genMarkersAndTextOfPathDelay: check your input : evenNumberList($evenNumberList)(num: [llength $evenNumberList]) and textList($textList)(num: [llength $textList]) need equal!!!" 
  }
  set locationFromPointToPointList [add_markers_and_text_for_point_list $evenNumberList $minLengthOfLine $sizeOfText 0]
  if {[llength $locationFromPointToPointList] != [llength $textList]} {
    error "proc genCmd_genMarkersAndTextOfPathDelay: check your input : list that get location and processed(num: [llength $evenNumberList]) and textList($textList)(num: [llength $textList]) need equal!!!" 
  }
  set cmdsList [list ]
  set i 0
  foreach temp_list $locationFromPointToPointList temp_text $textList {
    incr i
    lassign $temp_list from_to box
    lassign $from_to temp_from temp_to
    if {$ifAddMarkersForPin} {lappend cmdsList "add_gui_marker -color $color -pt $temp_to -type $markerShapeType -name $i"}
    lappend cmdsList "add_gui_shape -layer $layerOfText -line \{$temp_from $temp_to\} -arrow"
    lappend cmdsList "add_gui_text -layer $layerOfText -pt $temp_from -box \{$box\} -label $temp_text"
  }
  return $cmdsList
}

define_proc_arguments genCmd_genMarkersAndTextOfPathDelay \
  -info "gen cmd for generating markers and text of delay of path"\
  set typeForMarkersAndText "add" ; # add|delete
  set evenNumberList        {}
  set textList              {}
  set sizeOfText             {} 
  set layerOfText           8 ; # routing layer name, can also use number
  set ifAddMarkersForPin    1 ; # 1|0
  set color                 "cyan" ; # red blue green yellow magenta cyan pink orange brown purple violet teal olive gold maroon wheat
  set markerShapeType       "STAR" ; # X|TICK|STAR
  -define_args {
    {-typeForMarkersAndText "specify the type of actions for markers and text" oneOfString one_of_string {optional value_type {values {add delete}}}}
    {-evenNumberList "specify the even number list consisted of points pt" AList list optional}
    {-textList "specify the list of text that need add when type is 'add'" AList list optional}
    {-minLengthOfLine "specify the min length of line that is used to add_line" AFloat float optional}
    {-sizeOfText "specify the size of text, format: {width height}" AList list optional}
    {-layerOfText "specify the layer of text that need add to" AString string optional}
    {-ifAddMarkersForPin "if adding markers for pin" oneOfString one_of_string {optional value_type {values {0 1}}}}
    {-color "specify the color of markers"}
    {-markerShapeType ""}
  }

#!/bin/tclsh
# --------------------------
# author    : sar song
# date      : 2025/09/23 23:14:45 Tuesday
# label     : gui_proc
#   tcl  -> (atomic_proc|display_proc|gui_proc|task_proc|dump_proc|check_proc|math_proc|package_proc|test_proc|datatype_proc|db_proc|flow_proc|report_proc|cross_lang_proc|misc_proc)
#   perl -> (format_sub|getInfo_sub|perl_task)
# descrip   : According to the input list of even-numbered items, each item is a pin name, and every two items form a pair. Pins in a pair must be on the same net. If they are 
#             not on the same net, an error message will be triggered. You can choose to use functions like "flight line" or "whole_net" to highlight the connection relationship, 
#             which will be accompanied by arrows indicating the direction. It is possible to customize a circular list of highlight colors (including colors for nets and insts), 
#             and you can specify whether to highlight insts or nets.
# return    : cmds list
# ref       : link url
# --------------------------
source ../packages/logic_AND_OR.package.tcl; # eo
proc genCmd_highlightTimingPathBasedOnListOfEvenNumberedItems {args} {
  set evenNumberList     {} ; # must be even number list
  set modeOfConnect "whole_net" ; # whole_net|flight_line
  set ifWithArrow   1; # 1|0
  set colorsIndexLoopListsForNet {60 50 62 63 61 55 52 4 6 14 15 17 28 29 31 56 57 61 64 42} ; # 20 items
  set colorsIndexLoopListsForInst {1 2 3 5 7 9 10 11 14 15 17 19 20 21 24 22 25 28 30 32} ; # 20 items
  set indexOfColorsForNetInst 0 ; # 0-19
  parse_proc_arguments -args $args opt
  foreach arg [array names opt] {
    regsub -- "-" $arg "" var
    set $var $opt($arg)
  }
  set indexOfColorsForNetInst [expr {$indexOfColorsForNetInst % [expr {([llength $colorsIndexLoopListsForNet] + [llength $colorsIndexLoopListsForInst]) / 2 }]}]
  if {[expr {[llength $evenNumberList] % 2}]} {
    error "proc genCmd_highlightTimingPathBasedOnListOfEvenNumberedItems: check your evenNumberList（num: [llength $evenNumberList]) must be even number list!!!" 
  }
  set hiliteCmdsList [list ]
  foreach {pin1 pin2} $evenNumberList {
    set pin1_net [dbget [dbget top.insts.instTerms.name $pin1 -p].net.name -e] 
    set pin2_net [dbget [dbget top.insts.instTerms.name $pin2 -p].net.name -e]
    if {$pin1_net == "" || $pin2_net == ""} {
      error "proc genCmd_highlightTimingPathBasedOnListOfEvenNumberedItems: check your input: pin($pin1_net or $pin2_net) is not net to connect!!!" 
    } else {
      if {$pin1_net != $pin2_net} {
        error "proc genCmd_highlightTimingPathBasedOnListOfEvenNumberedItems: check your input: both pins($pin1_net and $pin2_net) are not on same net!!!" 
      } else {
        set netColor [lindex $colorsIndexLoopListsForNet $indexOfColorsForNetInst]
        set instColor [lindex $colorsIndexLoopListsForInst $indexOfColorsForNetInst]
        lappend hiliteCmdsList "highlight_pin_connection -from_pin $pin1 -to_pin $pin2 -mode $modeOfConnect [eo $ifWithArrow "-with_arrow" ""] -net_color_index $netColor -inst_color_index $instColor"
      }
    }
  }
  return $hiliteCmdsList
}

define_proc_arguments genCmd_highlightTimingPathBasedOnListOfEvenNumberedItems \
  -info "gen cmd for highlighting timing path based on list of even-numbered items"\
  -define_args {
    {-modeOfConnect "specify the type of eco" oneOfString one_of_string {optional value_type {values {whole_net flight_line}}}}
    {-evenNumberList "specify inst to eco when type is add/delete" AList list optional}
    {-ifWithArrow "if using arrow on line" oneOfString one_of_string {optional value_type {values {1 0}}}}
    {-colorsIndexLoopListsForNet "specify the colors index loop lists for net color" AList list optional}
    {-colorsIndexLoopListsForInst "specify the colors index loop lists for inst color" AList list optional}
    {-indexOfColorsForNetInst "specify the index of Net and Inst color, it can get index with circle" AInt int optional}
  }


#!/bin/tclsh
# --------------------------
# author    : sar song
# date      : 2025/09/24 15:12:23 Wednesday
# label     : misc_proc
#   tcl  -> (atomic_proc|display_proc|gui_proc|task_proc|dump_proc|check_proc|math_proc|package_proc|test_proc|datatype_proc|db_proc|flow_proc|report_proc|cross_lang_proc|misc_proc)
#   perl -> (format_sub|getInfo_sub|perl_task)
# descrip   : Obtain the path pins that need to be highlighted from the report_timing (rpt) file of PT, and different paths can be automatically split based on keywords.
# return    : lists of even pins
# ref       : link url
# --------------------------
source ./common/split_timing_path.common.tcl; # split_timing_path
proc genCmd_getPurePinOfPath_fromTimingPathReport {args} {
  set reportTimingFile   ""
  set lineExpToSplitPath {^TE} ; # used to regexp
  set stdcellExp         {.*D\d+BWP(LVT)?} ; # don't use char '^' or '$'
  set startOfPath        {Point\s+} ; # end expression of launch timing path
  set endOfPath          {data arrival time} ; # end expression of launch timing path
  parse_proc_arguments -args $args opt
  foreach arg [array names opt] {
    regsub -- "-" $arg "" var
    set $var $opt($arg)
  }
  if {![file isfile $reportTimingFile]} {
    error "proc genCmd_getPurePinOfPath_fromTimingPathReport: check your input: file name ($reportTimingFile) is not found!!!" 
  }
  set fi [open $reportTimingFile r]
  set content [split [read $fi] \n]
  set stdcellExpToMatchLine [subst -nocommands -nobackslashes {($stdcellExp)}]
  set pinLines [lmap templine $content {
    if {[regexp $lineExpToSplitPath|$stdcellExpToMatchLine|$startOfPath|$endOfPath $templine]} {
      set temp $templine 
    }
  }]
  set purePinListWithSplieLine [lmap templine $pinLines {
    if {[regexp {^\s*$} $templine]} { continue }
    set indexOfStdCell [lsearch -regexp $templine $stdcellExpToMatchLine]
    if {$indexOfStdCell == -1} { 
      if {[regexp $startOfPath $templine]} { 
        set temp "START" 
      } elseif {[regexp $endOfPath $templine]} {
        set temp "END" 
      } elseif {[regexp $lineExpToSplitPath $templine]} {
        set temp "SPLIT"
      }
    } else {
      set pinName [lindex $templine [expr {$indexOfStdCell - 1}]]
    }
  }]
  set splitedPinList [split_timing_path $purePinListWithSplieLine]
  set filteredPinList [lmap tempList $splitedPinList {
    if {[llength $tempList] == 1} { continue } else {
      if {[join [lrange [split [lindex $tempList 0] "/"] 0 end-1] "/"] eq [join [lrange [split [lindex $tempList 1] "/"] 0 end-1] "/"]} {
        set tempList [lrange $tempList 1 end] 
      }
      if {[expr {[llength $tempList] % 2}]} {
        error "proc genCmd_highlightTimingPathBasedOnListOfEvenNumberedItems: check your path([join $tempList " - > "]) need be even number list(length: [llength $tempList]) !!!" 
      }
      foreach {pin1 pin2} $tempList {
        set net1 [dbget [dbget top.insts.instTerms.name $pin1 -p].net.name -e]
        set net2 [dbget [dbget top.insts.instTerms.name $pin2 -p].net.name -e]
        if {$net1 == "" || $net2 == ""} {
          error "proc genCmd_getPurePinOfPath_fromTimingPathReport: check your pinname($pin1 or $pin2) in rpt file($reportTimingFile), not found net!!!" 
        }
        if {$net1 != $net2} {
          error "proc genCmd_getPurePinOfPath_fromTimingPathReport: both pins($pin1 and $pin2) are not on same net(net1: $net1 , net2: $net2)!!!"
        }
      }
    }
    set temp $tempList
  }]
  return $filteredPinList
}

define_proc_arguments genCmd_getPurePinOfPath_fromTimingPathReport \
  -info "gen cmd for geting pure pin of path from timing path report, \n\t \
  Notice: This proc uses the report_timing rpt file generated by PT to match and \
  obtain pin names. It must display both the input pin and output pin names of the \
  inst, and must not only show the output pin name. In addition, after the pin name, \
  there must be a number of spaces followed by the format '(stdCellName)', because \
  the proc uses this positional relationship to obtain the pin name."\
  -define_args {
    {-reportTimingFile "specify the file name of report_timing" AString string optional}
    {-lineExpToSplitPath "specify expression of spliting timing path" AString string optional}
    {-stdcellExp "specify the expression of match stdcell name(of LibCells)" AString string optional}
    {-startOfPath "specify the start expression of timing path" AString string optional}
    {-endOfPath "specify the end expression of timing path" AString string optional}
  }
