#!/bin/tclsh
# --------------------------
# author    : sar song
# date      : 2025/08/17 12:55:06 Sunday
# label     : package_proc
#   -> (atomic_proc|display_proc|gui_proc|task_proc|dump_proc|check_proc|math_proc|package_proc|test_proc|datatype_proc|db_proc|misc_proc)
# descrip   : This proc automatically generates standardized file header comments with calling procedure name, author, 
#             timestamp, description, and usage, featuring aligned labels and auto-wrapped long text. It uses a loop 
#             to process comment fields, enabling easy extension with new labels.
# return    : provides consistent documentation of file origins and usage, improving code clarity and maintainability.
# ref       : link url
# --------------------------
alias sus "subst -nocommands -nobackslashes"
proc add_file_header {args} {
set fileID         ""
set proc_name      [lindex [info level 1] 0]
set author         "sar song"
set date 			     "auto"
set descrip        "None"
set usage          "None"
set line_width     150
set splitLineWidth 36
  parse_proc_arguments -args $args opt
  foreach arg [array names opt] {
    regsub -- "-" $arg "" var
    set $var $opt($arg)
  }
  # Get current time with specified format: %Y/%m/%d %H:%M:%S %A
  # %Y: 4-digit year, %m: 2-digit month, %d: 2-digit day
  # %H: 24-hour format hour, %M: minute, %S: second, %A: full weekday name
  if {$date == "auto"} {
    set current_date [clock format [clock seconds] -format "%Y/%m/%d %H:%M:%S %A"]
  } else {
    set current_date $date
  }
	# Define all labels with their corresponding values and wrap flags
  # Format: {label value wrap_needed}
  # NOTICE : value need only write variable name: like proc_name, instead of $proc_name !!!
  set fields [sus {
    {{Generated by} {$proc_name} 0}
    {{Author} {$author} 0}
    {{Date} {$current_date} 0}
    {{Description} {$descrip} 1}
    {{Usage} {$usage} 1}
  }]
  # Calculate maximum label length for colon alignment
  set max_label_length 0
  foreach field $fields {
    lassign $field label value wrap_needed
    set len [string length $label]
    if {$len > $max_label_length} {
      set max_label_length $len
    }
  }
  
  # Function to wrap text to specified width
  proc wrap_text {text width} {
    set wrapped [list]
    set words [split $text]
    set current_line ""
    
    foreach word $words {
      if {[string length "$current_line $word"] <= $width} {
        if {$current_line eq ""} {
          set current_line $word
        } else {
          append current_line " $word"
        }
      } else {
        lappend wrapped $current_line
        set current_line $word
      }
    }
    if {$current_line ne ""} {
      lappend wrapped $current_line
    }
    return $wrapped
  }
  # Write top separator with optimal visual length
  puts $fileID "# [string repeat "-" $splitLineWidth]"
  
# Process all fields using foreach loop
  foreach field $fields {
    lassign $field label value wrap_needed
    # Calculate spaces for colon alignment
    set spaces [expr {$max_label_length - [string length $label]}]
    set indent [string repeat " " $spaces]
    if {$wrap_needed} {
      # Handle fields that need text wrapping
      puts -nonewline $fileID "# $indent$label :"
      set wrap_width [expr {$line_width - $max_label_length - 2}]
      set wrapped_text [wrap_text $value $wrap_width]
      set text_indent [string repeat " " [expr {$max_label_length + 2}]]
      set firstLine 0
      foreach line $wrapped_text {
        incr firstLine
        if {$firstLine == 1} {puts $fileID " $line"} else {
          puts $fileID "# $text_indent$line"
        }
      }
    } else {
      # Handle fields with single-line values
      puts $fileID "# $indent$label : $value"
    }
  }
  # Write bottom separator
  puts $fileID "# [string repeat "-" $splitLineWidth]"
  puts $fileID ""
  
  # Clean up the helper proc
  rename wrap_text ""
}

define_proc_arguments add_file_header \
  -info "add file header"\
  -define_args {
    {-fileID "specify fileID, which you need write to" AString string required}
    {-proc_name "specify proc_name \"Generated by\"" AString string optional}
    {-author "sepcify the author" AString string optional}
    {-date "specify the date" AString string optional}
    {-descrip "sepcify the detailed description for this file" AString string optional}
    {-usage "specify the usage of file" AString string optional}
    {-line_width "specify the max width of every line" AInt int optional}
    {-splitLineWidth "specify the fixed width of split line" AInt int optional}
  }

